### ISSUE TITLE
Authorization token doesnt get the generated password during the terraform plan

### ISSUE THREAD

**Issue by ZuzkaP** [clouddrove/terraform-aws-elasticache#56] opened 2023-08-25 09:05 UTC
We would like to address an issue related to the module you have created. Currently, we are facing a challenge when using the module. Below are the details.

1. We try to generate a random password using following resource and after that assign it to auth_token variable.
# Generate radnom password
resource "random_password" "this" {
  length           = 25
  special          = false
}

2. We try to plan but we run to the issue that the password is not provided to auth_token at the moment of planning as it hasnt been created yet before.

Plan: 6 to add, 3 to change, 2 to destroy.
╷
│ Error: Invalid count argument
│ 
│   on .terraform/modules/elasticache_defi.elasticache/main.tf line 235, in resource "aws_ssm_parameter" "secret":
│  235:   count = var.auth_token != null ? 1 : 0
│ 
│ The "count" value depends on resource attributes that cannot be determined
│ until apply, so Terraform cannot predict how many instances will be
│ created. To work around this, use the -target argument to first apply only
│ the resources that the count depends on.

One idea how to solve this is to plan and  target the generation of the password and only after applying execute the full terraform plan again but this is not convenient solution for us.

We need to have the whole module ready in 1 go.

Any recommended solutions?

**Comment by anmolnagpal** [comment] 2023-09-04 00:12
@ZuzkaP  sorry for the delay, team will come back to you soon. 

Thanks

**Comment by vaibhav7797** [comment] 2023-09-06 17:08
"Hello @ZuzkaP , I appreciate your contribution and taking the time to report the issue in our GitHub repository. We fixed the issue that you raised and now you can generate the password during terraform plan. However I've released the new release tagged as `2.0.1`. The issue is now resolved, and I'm closing it.

**Closed by vaibhav7797** 2023-09-06 17:08 UTC
Labels: bug
